Enable clang-tidy check for null function pointers (#835)
* Enable clang-tidy check for null function pointers

See

 https://clang.llvm.org/docs/analyzer/checkers.html#core-callandmessage

for more info.

Fixes the following (unlikely) situation:

/home/simon/git/herbstluftwm/src/rootcommands.cpp:108:18: error: Called C++ object pointer is null [clang-analyzer-core.CallAndMessage,-warnings-as-errors]
    auto child = root->child(attr_path.first);
                 ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:72:9: note: Assuming the condition is false
    if (!p.empty()) {
        ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:72:5: note: Taking false branch
    if (!p.empty()) {
    ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:78:9: note: Assuming 'o' is null
    if (o && new_value.empty()) {
        ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:78:11: note: Left side of '&&' is false
    if (o && new_value.empty()) {
          ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:83:20: note: Calling 'RootCommands::getAttribute'
    Attribute* a = getAttribute(path, output);
                   ^
/home/simon/git/herbstluftwm/src/rootcommands.cpp:108:18: note: Called C++ object pointer is null
    auto child = root->child(attr_path.first);

* Use reference instead of pointer

* Update comment

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>